unstable_features = true

indent_style = "Block"
brace_style = "PreferSameLine"
max_width = 82

merge_imports = true
imports_layout = "HorizontalVertical"

inline_attribute_width = 80
struct_field_align_threshold = 30
enum_discrim_align_threshold = 30
overflow_delimited_expr = true
empty_item_single_line = true
reorder_impl_items = true
binop_separator = "Back"

fn_single_line = true
fn_args_layout="Vertical"
# fn_call_style = "Block"

wrap_comments = true
# format_code_in_doc_comments = true

use_field_init_shorthand = true
use_try_shorthand = true

# hide_parse_errors=true
